version: '3.1'

services:
  jrtb-db:
    image: mysql:8.0
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_DATABASE: 'dev_jrtb_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'dev_jrtb_db_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'dev_jrtb_db_password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
